import React, { FC } from "react";
import style from "./style.module.scss";

const WIREFRAME_IMAGES: Record<string, string> = {
  "activity-recieve.svg": require("@assets/svg/wireframe/activity-recieve.svg"),
  "activity-receive.svg": require("@assets/svg/wireframe/activity-recieve.svg"),
  "activity-send.svg": require("@assets/svg/wireframe/activity-send.svg"),
  "activity-stake.svg": require("@assets/svg/wireframe/activity-stake.svg"),
  "alert.svg": require("@assets/svg/wireframe/alert.svg"),
  "apple-logo.svg": require("@assets/svg/wireframe/apple-logo.svg"),
  "arrow-down-gradient.svg": require("@assets/svg/wireframe/arrow-down-gradient.svg"),
  "arrow-down-up-across-line.svg": require("@assets/svg/wireframe/arrow-down-up-across-line.svg"),
  "arrow-down.svg": require("@assets/svg/wireframe/arrow-down.svg"),
  "arrow-right.svg": require("@assets/svg/wireframe/arrow-right.svg"),
  "arrow-up-1.svg": require("@assets/svg/wireframe/arrow-up-1.svg"),
  "arrow-up-gradient.svg": require("@assets/svg/wireframe/arrow-up-gradient.svg"),
  "arrow-up.svg": require("@assets/svg/wireframe/arrow-up.svg"),
  "arrow.svg": require("@assets/svg/wireframe/arrow.svg"),
  "asi-black-circle.svg": require("@assets/svg/wireframe/asi-black-circle.svg"),
  "asi-send.svg": require("@assets/svg/wireframe/asi-send.svg"),
  "asi-staked.svg": require("@assets/svg/wireframe/asi-staked.svg"),
  "at.svg": require("@assets/svg/wireframe/at.svg"),
  "auto-lock-timer.svg": require("@assets/svg/wireframe/auto-lock-timer.svg"),
  "auto-lock.svg": require("@assets/svg/wireframe/auto-lock.svg"),
  "axl-bridge.svg": require("@assets/svg/wireframe/axl-bridge.svg"),
  "back-button.svg": require("@assets/svg/wireframe/back-button.svg"),
  "bg-onboarding.svg": require("@assets/svg/wireframe/bg-onboarding.svg"),
  "bg-register.svg": require("@assets/svg/wireframe/bg-register.svg"),
  "bg-returning-user.svg": require("@assets/svg/wireframe/bg-returning-user.svg"),
  "bg.svg": require("@assets/svg/wireframe/bg.svg"),
  "bridge-history.svg": require("@assets/svg/wireframe/bridge-history.svg"),
  "bridge.svg": require("@assets/svg/wireframe/bridge.svg"),
  "btn-close.svg": require("@assets/svg/wireframe/btn-close.svg"),
  "buy.svg": require("@assets/svg/wireframe/buy.svg"),
  "chain-list-access.svg": require("@assets/svg/wireframe/chain-list-access.svg"),
  "change.svg": require("@assets/svg/wireframe/change.svg"),
  "changeNet.svg": require("@assets/svg/wireframe/changeNet.svg"),
  "chat-alt.svg": require("@assets/svg/wireframe/chat-alt.svg"),
  "chatIcon.svg": require("@assets/svg/wireframe/chatIcon.svg"),
  "check.svg": require("@assets/svg/wireframe/check.svg"),
  "chevron-down-rewards.svg": require("@assets/svg/wireframe/chevron-down-rewards.svg"),
  "chevron-down.svg": require("@assets/svg/wireframe/chevron-down.svg"),
  "chevron.svg": require("@assets/svg/wireframe/chevron.svg"),
  "circle-check.svg": require("@assets/svg/wireframe/circle-check.svg"),
  "circle-xmark.svg": require("@assets/svg/wireframe/circle-xmark.svg"),
  "clock.svg": require("@assets/svg/wireframe/clock.svg"),
  "close.svg": require("@assets/svg/wireframe/close.svg"),
  "closeImage.svg": require("@assets/svg/wireframe/closeImage.svg"),
  "contract-integration-transparent.svg": require("@assets/svg/wireframe/contract-integration-transparent.svg"),
  "contract-interaction.svg": require("@assets/svg/wireframe/contract-interaction.svg"),
  "copy.svg": require("@assets/svg/wireframe/copy.svg"),
  "copyGrey.svg": require("@assets/svg/wireframe/copyGrey.svg"),
  "currency.svg": require("@assets/svg/wireframe/currency.svg"),
  "delete-hero.svg": require("@assets/svg/wireframe/delete-hero.svg"),
  "delete-hero2.svg": require("@assets/svg/wireframe/delete-hero2.svg"),
  "delete.svg": require("@assets/svg/wireframe/delete.svg"),
  "deleteDark.svg": require("@assets/svg/wireframe/deleteDark.svg"),
  "dorado.svg": require("@assets/svg/wireframe/dorado.svg"),
  "earn.svg": require("@assets/svg/wireframe/earn.svg"),
  "eth.svg": require("@assets/svg/wireframe/eth.svg"),
  "external-link-vesting.svg": require("@assets/svg/wireframe/external-link-vesting.svg"),
  "external-link.svg": require("@assets/svg/wireframe/external-link.svg"),
  "eye-2.svg": require("@assets/svg/wireframe/eye-2.svg"),
  "eye.svg": require("@assets/svg/wireframe/eye.svg"),
  "fetch-logo.svg": require("@assets/svg/wireframe/fetch-logo.svg"),
  "filter-check.svg": require("@assets/svg/wireframe/filter-check.svg"),
  "filter.svg": require("@assets/svg/wireframe/filter.svg"),
  "fns.svg": require("@assets/svg/wireframe/fns.svg"),
  "gem.svg": require("@assets/svg/wireframe/gem.svg"),
  "google-icon.svg": require("@assets/svg/wireframe/google-icon.svg"),
  "google-logo.svg": require("@assets/svg/wireframe/google-logo.svg"),
  "guide.svg": require("@assets/svg/wireframe/guide.svg"),
  "hand-holding-seedling.svg": require("@assets/svg/wireframe/hand-holding-seedling.svg"),
  "hardware.svg": require("@assets/svg/wireframe/hardware.svg"),
  "ibc-transfer-v2.svg": require("@assets/svg/wireframe/ibc-transfer-v2.svg"),
  "ibc-transfer.svg": require("@assets/svg/wireframe/ibc-transfer.svg"),
  "ic_autolock.svg": require("@assets/svg/wireframe/ic_autolock.svg"),
  "ic_claimrewards.png": require("@assets/svg/wireframe/ic_claimrewards.png"),
  "ic_claimrewards.svg": require("@assets/svg/wireframe/ic_claimrewards.svg"),
  "ic_staking.svg": require("@assets/svg/wireframe/ic_staking.svg"),
  "import-icon.svg": require("@assets/svg/wireframe/import-icon.svg"),
  "Injective-logo 2.svg": require("@assets/svg/wireframe/Injective-logo 2.svg"),
  "key-icon.png": require("@assets/svg/wireframe/key-icon.png"),
  "key.svg": require("@assets/svg/wireframe/key.svg"),
  "language.svg": require("@assets/svg/wireframe/language.svg"),
  "ledger-indicator.svg": require("@assets/svg/wireframe/ledger-indicator.svg"),
  "legend-dark-green-long.svg": require("@assets/svg/wireframe/legend-dark-green-long.svg"),
  "legend-dark-green.svg": require("@assets/svg/wireframe/legend-dark-green.svg"),
  "legend-light-green-long.svg": require("@assets/svg/wireframe/legend-light-green-long.svg"),
  "legend-light-green.svg": require("@assets/svg/wireframe/legend-light-green.svg"),
  "legend-light-orange.svg": require("@assets/svg/wireframe/legend-light-orange.svg"),
  "legend-sky-long.svg": require("@assets/svg/wireframe/legend-sky-long.svg"),
  "legend-sky.svg": require("@assets/svg/wireframe/legend-sky.svg"),
  "line-1.svg": require("@assets/svg/wireframe/line-1.svg"),
  "Line.svg": require("@assets/svg/wireframe/Line.svg"),
  "lock.svg": require("@assets/svg/wireframe/lock.svg"),
  "logo-small.svg": require("@assets/svg/wireframe/logo-small.svg"),
  "LogoV2.svg": require("@assets/svg/wireframe/LogoV2.svg"),
  "manage-tokens.svg": require("@assets/svg/wireframe/manage-tokens.svg"),
  "metamask-icon.svg": require("@assets/svg/wireframe/metamask-icon.svg"),
  "minus.svg": require("@assets/svg/wireframe/minus.svg"),
  "new-clock-white.svg": require("@assets/svg/wireframe/new-clock-white.svg"),
  "new-clock.svg": require("@assets/svg/wireframe/new-clock.svg"),
  "new-home.svg": require("@assets/svg/wireframe/new-home.svg"),
  "new-inbox.svg": require("@assets/svg/wireframe/new-inbox.svg"),
  "new-more.svg": require("@assets/svg/wireframe/new-more.svg"),
  "new-robot.svg": require("@assets/svg/wireframe/new-robot.svg"),
  "no-activity.svg": require("@assets/svg/wireframe/no-activity.svg"),
  "no-address.svg": require("@assets/svg/wireframe/no-address.svg"),
  "notification.svg": require("@assets/svg/wireframe/notification.svg"),
  "openAsset.svg": require("@assets/svg/wireframe/openAsset.svg"),
  "osmosis.svg": require("@assets/svg/wireframe/osmosis.svg"),
  "percentage.svg": require("@assets/svg/wireframe/percentage.svg"),
  "pin-arrow.svg": require("@assets/svg/wireframe/pin-arrow.svg"),
  "plus-icon.svg": require("@assets/svg/wireframe/plus-icon.svg"),
  "plus-minus-gradient.svg": require("@assets/svg/wireframe/plus-minus-gradient.svg"),
  "plus-minus.svg": require("@assets/svg/wireframe/plus-minus.svg"),
  "plus.svg": require("@assets/svg/wireframe/plus.svg"),
  "proposal.svg": require("@assets/svg/wireframe/proposal.svg"),
  "qrcode.svg": require("@assets/svg/wireframe/qrcode.svg"),
  "rename.svg": require("@assets/svg/wireframe/rename.svg"),
  "rocket.svg": require("@assets/svg/wireframe/rocket.svg"),
  "search.svg": require("@assets/svg/wireframe/search.svg"),
  "security.svg": require("@assets/svg/wireframe/security.svg"),
  "selected-home.svg": require("@assets/svg/wireframe/selected-home.svg"),
  "selected-inbox.svg": require("@assets/svg/wireframe/selected-inbox.svg"),
  "selected-more.svg": require("@assets/svg/wireframe/selected-more.svg"),
  "selected-stake.svg": require("@assets/svg/wireframe/selected-stake.svg"),
  "setting.svg": require("@assets/svg/wireframe/setting.svg"),
  "sidepanel.svg": require("@assets/svg/wireframe/sidepanel.svg"),
  "sign-out.svg": require("@assets/svg/wireframe/sign-out.svg"),
  "sort.svg": require("@assets/svg/wireframe/sort.svg"),
  "stake-bottom-icon-new.svg": require("@assets/svg/wireframe/stake-bottom-icon-new.svg"),
  "stake-tab.svg": require("@assets/svg/wireframe/stake-tab.svg"),
  "stake-v2.svg": require("@assets/svg/wireframe/stake-v2.svg"),
  "stake.svg": require("@assets/svg/wireframe/stake.svg"),
  "swap.svg": require("@assets/svg/wireframe/swap.svg"),
  "Title.svg": require("@assets/svg/wireframe/Title.svg"),
  "transx-failed.svg": require("@assets/svg/wireframe/transx-failed.svg"),
  "transx-pending.svg": require("@assets/svg/wireframe/transx-pending.svg"),
  "transx-success.svg": require("@assets/svg/wireframe/transx-success.svg"),
  "user.svg": require("@assets/svg/wireframe/user.svg"),
  "voting-power.svg": require("@assets/svg/wireframe/voting-power.svg"),
  "wallet-access-permission.svg": require("@assets/svg/wireframe/wallet-access-permission.svg"),
  "wallet-new.svg": require("@assets/svg/wireframe/wallet-new.svg"),
  "wallet-version.svg": require("@assets/svg/wireframe/wallet-version.svg"),
  "wallet.svg": require("@assets/svg/wireframe/wallet.svg"),
  "warning.svg": require("@assets/svg/wireframe/warning.svg"),
  "welcome-content.svg": require("@assets/svg/wireframe/welcome-content.svg"),
  "welcome-frame.svg": require("@assets/svg/wireframe/welcome-frame.svg"),
  "xmark.svg": require("@assets/svg/wireframe/xmark.svg"),
};

export interface Props {
  title: string;
  image?: keyof typeof WIREFRAME_IMAGES | null;
  onClick: () => void;
  disabled?: boolean;
}

export const ActionButton: FC<Props> = ({
  title,
  image,
  onClick,
  disabled,
}) => {
  const src = image != null ? WIREFRAME_IMAGES[image] : undefined;
  return (
    <button disabled={disabled} className={style["action"]} onClick={onClick}>
      {src != null && <img src={src} alt="" />}
      <div className={style["img-title"]}>{title}</div>
    </button>
  );
};
